# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Think Tutor
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Get tutoring from experts. Think Tutor is a private tutoring cooperative 
  with in-person tutoring in Evanston and remote tutoring worldwide. Our tutors
  have or are working on doctorates from top schools in the subjects they teach.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thinktutor.org" # the base hostname & protocol for your site, e.g. http://example.com
cdn: "ajsxgydazo.cloudimg.io/v7" # CDN prefix to put in front of images
# twitter_username: jekyllrb
# github_username:  jekyll

collections:
  subjects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "subjects"
    values:
      layout: "subject"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets

# Build settings
markdown: kramdown
sass:
  style: compressed
compress_html:
  comments: all
  endings: all
  startings: all

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
